language: generic
install:
  - git clone https://github.com/thinca/vim-themis --branch v1.5 --single-branch --depth 1
  - git clone https://github.com/kana/vim-operator-user
script:
  - vim --version
  - vim-themis/bin/themis --reporter spec --runtimepath vim-operator-user
